# Generated by Django 4.2.3 on 2023-07-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blogapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("bio", models.TextField()),
            ],
        ),
    ]
